
// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type { BaseClientOptions } from "@xata.io/client";

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "postgresql://xata:4ji1aves0zDWFKdOOEmkkonPDE671Ig3vwXyBr2QBtweHrRXv6GvCxOVN4WjIVoO@o363cflsht6tt3sr589mcke1ms.us-east-1.xata.tech/postgres?sslmode=require",
  apiKey: process.env.XATA_API_KEY,
  branch: "master",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};